### ISSUE TITLE
Compatible With Element API V1?

### ISSUE THREAD

**Issue by kieranstartup** [OliveStudio/olivemenus#10]
I'm using the [Element API V1](https://github.com/craftcms/element-api/tree/v1) to display my content and I'm wondering if Olive Menus is compatible with the API and if so, would you be able to provide a brief example? 

Under Endpoint Configuration Settings > elementType the Read.me says it accepts _any plugin-based element type class names_ but I'm fairly new to Craft and I'm unsure what that would be in relation to Olive Menus.

Thanks!

**Comment by alinistrate** [comment]
Hello Kieran,

We never used this plugin and we don’t really know if it is compatible.
We will research and get back to you with an answer.

Thanks,
Alin


[Olive Studio]<http://www.olivestudio.net/>

Istrate Alin Dumitru
OLIVE STUDIO
Romania, Sibiu, 5 Gen. Magheru Str.
Skype: alin.istrate2

**Comment by kieranstartup** [comment]
Hey Alin,

Thanks for getting back so quickly and for offering to look into the plugin for me, much appreciated! 

If it's not compatible, it's no major problem.

Thanks!

**Comment by alinistrate** [comment]
Hello Kieran,

I checked and it is not compatible with Element API V1

Thanks,
Alin


[Olive Studio]<http://www.olivestudio.net/>

Istrate Alin Dumitru
OLIVE STUDIO
Romania, Sibiu, 5 Gen. Magheru Str.
Skype: alin.istrate2

**Comment by kieranstartup** [comment]
Hey Alin,

Thanks for taking the time to see if it was compatible, much appreciated!
