### ISSUE TITLE
Craft 3

### ISSUE THREAD

**Issue by calder12** [OliveStudio/olivemenus#14]
Hi, just curious if you have any intention of porting this plugin to Craft 3? Thanks!

**Comment by neagucatalinmihai** [comment]
@calder12 , we are working on it 😃 . We will let you know as soon as it's ready.

**Comment by kdouglass** [comment]
Hi, just wondering if there was an update for the Craft 3 release?

**Comment by alinistrate** [comment]
Hello @calder12 
We just released the Craft 3 plugin version. Please note that the Craft 2 version can be found under Tags 2.0.0

Thank you,
Alin
