### ISSUE TITLE
Typos and inconsistencies in docs (wiki and README)

### ISSUE THREAD

**Issue by missmatsuko** [OliveStudio/olivemenus#16]
There's some typos in the the docs.
e.g. "Asign" should be "Assign" in https://github.com/OliveStudio/olivemenus/wiki/07.-Asign-data-attribute 

Also, the name of the plugin is written as "Olivemenus", "Olive Menus" and "olivemenus" in the wiki and README. Since the Craft 3 plugin page and README graphic both use "Olivemenus", should we use that style where applicable?

I can work on this, but I think I'd need permissions to make wiki changes:
https://help.github.com/articles/changing-access-permissions-for-wikis/

**Comment by alinistrate** [comment]
Hello Matsuko,
Nice meeting you! Thank you for noticing. 

I updated the permissions and allowed you to work on the Wiki. 

Alin
