### ISSUE TITLE
Add front-end method to loop through menu items/customize markup

### ISSUE THREAD

**Issue by missmatsuko** [OliveStudio/olivemenus#17]
I used to use the [Navee plugin](https://github.com/fromtheoutfit/navee) for menus in Craft 2, and I liked how I could loop through the menu items in Twig to further customize the markup. 

Example:
```
{% set navConfig = {
        'startwithActive' : true,
        'maxDepth' : 2,
        'activeClassOnAncestors' : true,
        'ancestorActiveClass' : 'activeAncestor',
    } %}

{% set navigation = craft.navee.getNav('mainNavigation', navConfig) %}

<ul>
    {% nav node in navigation %}
        <li{% if node.class %} class="{{ node.class }}"{% endif %}>
            <a href="{{ node.link }}">{{ node.title }}</a>
            {% ifchildren %}
                <ul>{% children %}</ul>
            {% endifchildren %}
        </li>
    {% endnav %}
</ul>
```

Can we add this feature? I played with the plugin code a little and I think I can get started (maybe with some direction).

**Comment by alinistrate** [comment]
Hello Matsuko,

You can fork the repository and start working on this feature. It will be a great improvement. We don't have the availability currently to do it.


Thanks,

Alin


________________________________
