### ISSUE TITLE
Active class

### ISSUE THREAD

**Issue by Superjo149** [OliveStudio/olivemenus#2]
Hi

The active class doesn't seem to be displaying

**Comment by neagucatalinmihai** [comment]
Hello,
The plugins has the functionality to add the "active" class to the anchor element when viewing a menu selected page. Can we see your setup more closely to see what the problem is?

Thanks

**Comment by Superjo149** [comment]
I'm sorry for bothering, I closed it because I found the issue.

The plugin uses the server name variable, but this was not configured the same as my craft siteurl. So it was not showing correctly.

**Comment by neagucatalinmihai** [comment]
Great, thanks!
