### ISSUE TITLE
List of entries not shown

### ISSUE THREAD

**Issue by gudehus** [OliveStudio/olivemenus#20]
When I try to select an entry of a section the list is not displayed. The PlugIn recognized the section and if there are entries bit none are shown. Also the search for entries isn't working.
<img width="308" alt="image" src="https://user-images.githubusercontent.com/239830/45096715-70d75f00-b121-11e8-93cd-39cd7b9355dc.png">

PHP version | 7.1.10
MySQL 5.6.19
GD 7.1.10
Craft Solo 3.0.23.1

**Comment by alinistrate** [comment]
Hello,
We are looking into this issue and deploy a fix as fast as possible.

Thank you,
Alin

**Comment by alinistrate** [comment]
Hello,

We are not able to replicate this issue. Can you please make sure you have the latest plugin version installed?

thanks,
Alin

**Comment by gudehus** [comment]
Everything is on the latest version.

Here is the login to the backend if you want to have a look.

User: admin
Password: wo5u4de4



mit freundlichen Grüßen
Jörg Gudehus

IT-Consultant

Holsteinische Straße 4
10717 Berlin
+49 151 15674619
gudehus@mac.com
www.joerggudehus.de

**Comment by alinistrate** [comment]
Hello,

Thank you, we are looking into it and let you know when the issue is fixed.

Thanks,
Alin

**Comment by gudehus** [comment]
The Url is http://neu.tatwerk.eu/admin/ <http://neu.tatwerk.eu/admin/>

thanks


mit freundlichen Grüßen
Jörg Gudehus

IT-Consultant

Holsteinische Straße 4
10717 Berlin
+49 151 15674619
gudehus@mac.com
www.joerggudehus.de

**Comment by alinistrate** [comment]
Hi All,

We managed to find the issue and fixed it. Please take the latest version.

We updated the plugin repository to be able to update.

Thanks,
Alin
