### ISSUE TITLE
Breadcrumb and selected Parent

### ISSUE THREAD

**Issue by tombauer** [OliveStudio/olivemenus#21]
Is it possible to mark the parent of a active subitem also with a active status (with a css class like "active_subitem", that the output would look like this:
`<div class="menu">`
    ` <ul class="">`
         ` <li id="menu-item-5" class="menu-item active_subitem">`
          `   <a class="" href="asdf">asfd</a>`
      `    <ul class="sub-menu">`
           `   <li id="menu-item-6" class="menu-item  current-menu-item">`
           `      <a class=" active" href="http://craft3.kreisvier.com/">Active Submenu</a>`
          `    </li>`
       `   </ul>`
      `    </li>`
   `  </ul>`
` </div>`

Is it possible to get a Breadcrumb of the menu? 
PS: Thanks for the already great plugin 👍

**Comment by alinistrate** [comment]
Hello Tom,

Thank you for this feedback. Currently, we don't have the resource available to do it. If you want you can contribute by forking the repository and doing it. 
We will approve the pull request if everything looks good.

Regarding the breadcrumb of the menu, we are not planning to develop such a feature. If you need this feature we can always do a custom development for you. If this is something that you want I can do a development cost estimate and send it to you.

Thank you,
Alin
