### ISSUE TITLE
Translation of menu items

### ISSUE THREAD

**Issue by gudehus** [OliveStudio/olivemenus#22]
Everything is working fine, but the menu titles are staying in the language of the main site.
The urls are working correctly.

**Comment by alinistrate** [comment]
Hi,
Thanks for finding this issue. 
We are currently working on it and will release a new version soon.

Thanks,
Alin

**Comment by christophstockinger** [comment]
Any news?  @alinistrate

**Comment by alinistrate** [comment]
We are currently working on this feature and it will be ready in the next couple of weeks.

Thank you,
Alin

[https://www.olivestudio.net/Alin-Istrate.jpg]
Alin Istrate
Tech Lead
Olive Studio
m:
+40745180103
a:
Romania, Sibiu, General Magheru 5
w:
www.olivestudio.net<http://www.olivestudio.net>  e: alin.istrate@olivestudio.net<mailto:alin.istrate@olivestudio.net>
s:
alin.istrate2

**Comment by JorgeAnzola** [comment]
Is there any update on this? Thanks!

**Comment by martijnvanonz** [comment]
I have a multisite and multi-locale setup and I can only choose the singles from the main site.

**Comment by BSBjorn** [comment]
@martijnvanonz, I have the same issue

**Comment by alinistrate** [comment]
Hi all,
Currently, the navigation is not multilingual. We have it on our pipeline but we didn't have any time to do it. As a workaround, if you still want to use the plugin I suggest creating separate menus for each language. I will let you know as soon as we release the next version including multilingual support.

Thank you,
Alin
