### ISSUE TITLE
Allow using categories as menu item

### ISSUE THREAD

**Issue by piotrpog** [OliveStudio/olivemenus#23]

**Comment by alinistrate** [comment]
Hi,

You already have this ability.

Thank you,
Alin

**Comment by piotrpog** [comment]
@alinistrate 
How can i do that? I dont see categories list in menu page. Even documentation doesnt mention categories:
"Then go ahead and open the menu and you will find lists of the Single entries, Channel items, Structure items and a Custom menu option."

**Comment by alinistrate** [comment]
Hello,
Please make sure you are using the latest version. We added this ability in a past release.

Thank you,
Alin

**Comment by piotrpog** [comment]
@alinistrate Im using latest version from plugin store.

**Comment by alinistrate** [comment]
Hello,
We added a new release that includes Category support. 

Thank you,
Alin
