### ISSUE TITLE
Plugin uninstallation fails

### ISSUE THREAD

**Issue by mtnorthrop** [OliveStudio/olivemenus#26]
Trying to uninstall this plugin causes an error in Craft 3. 

The reason appears to be that the migration that drops the `olivemenus` table is run before the migration that drops the `olivemenus_items` table.

This causes the uninstallation process to fail because the `olivemenus_items` table has a foreign key constraint on the `olivemenus` table, which means the `olivemenus` table cannot be dropped as long as the `olivemenus_items` table exists.

Until this issue has been fixed in a future update, the solution to this is to drop the `olivemenus_items` table manually first, and afterwards uninstall this plugin through the Craft control panel.

**Comment by alinistrate** [comment]
Hello @mtnorthrop 
Thank you for catching this issue. We fixed it and pushed a new release. Please use the 1.0.7 version.

Thanks,
Alin
