### ISSUE TITLE
Add HTML to the name field

### ISSUE THREAD

**Issue by tyssen** [OliveStudio/olivemenus#27]
I want to add markup for an SVG instead of text for a menu item. I can paste it in OK and it saves and the SVG shows up on the front-end but in the back end I get this:

![screen shot 2018-12-19 at 7 13 44 pm](https://user-images.githubusercontent.com/370290/50210608-510f3280-03c2-11e9-9377-701ad1409f5d.jpg)

and the next time you save a different menu item, it wipes it out and you have to add it again.

Any chance, the plugin could support pasting HTML into the name field?

**Comment by alinistrate** [comment]
Hi @tyssen 
This is not something we plan doing. I think the best approach is to create a new field to be able to add for each menu item an icon. 

This is something that we are considering but don't have time to implement now.

Thanks,
Alin
