### ISSUE TITLE
'sub-menu-ul-class' throwing exception on 1.0.6+

### ISSUE THREAD

**Issue by jhealey5** [OliveStudio/olivemenus#28]
I can't update past 1.0.5 without an exception being thrown regarding submenu classes:

![image](https://user-images.githubusercontent.com/1771431/51823190-98001a00-22d6-11e9-9bfa-69549a0ea093.png)

I can resolve it by adding a random class to the template function config:

```{{ craft.olivemenus.getMenuHTML('mainNav', { 'sub-menu-ul-class' : 'sub-menu' }) }}```

**Comment by alinistrate** [comment]
Hi @jhealey5 
Thanks for noticing this issue. We fixed it and pushed a new version.

Thanks,
Alin
