### ISSUE TITLE
Undefined index: sub-menu error

### ISSUE THREAD

**Issue by tyssen** [OliveStudio/olivemenus#29]
Craft 3.1.8
Olivemenus 1.0.7

When I try to create submenus by dragging an item and indenting it, I get an internal server error on the front end with this in the logs:

> Undefined index: sub-menu in /vendor/olivestudio/craftolivemenus/src/services/OlivemenusService.php:204

**Comment by alinistrate** [comment]
Hello @tyssen 
Thanks for sharing this issue. We fixed it and pushed to version 1.0.8

Thanks,
Alin
