### ISSUE TITLE
Plugin breaks when content is deleted

### ISSUE THREAD

**Issue by RoseDMH** [OliveStudio/olivemenus#30]
In templates/_menu-items.twig there seem to be no checks in place to exclude deleted single sections from the content which is made available in the menu editor console. This means that the plugin breaks completely as soon as you delete any singles, because empty entries are being found that then throw an error if you try to access the ID and so on.

**Comment by alinistrate** [comment]
Hello @RoseDMH 
Thanks for finding this issue. We solved it.

Thanks,
Alin
