### ISSUE TITLE
Is there a way that you can assign a menu item to open in a new tab?

### ISSUE THREAD

**Issue by rsi2940** [OliveStudio/olivemenus#32]

**Comment by rakesmh14** [comment]
Hello,
I have included target option for menu items. I hope this will help you to achieve open in new tab feature.
https://github.com/rakesmh14/olivemenus
<img width="471" alt="target-options" src="https://user-images.githubusercontent.com/6858928/71711992-851d9000-2e2b-11ea-85da-e42b8dc77dd7.png">
Frontend:
<img width="937" alt="target-option-fe" src="https://user-images.githubusercontent.com/6858928/71711996-8b137100-2e2b-11ea-975e-c11df9420a94.png">

Thank you!

**Comment by alinistrate** [comment]
@rakesmh14 

Thank you. I merged the pull request.

Alin

**Comment by rsi2940** [comment]
Thanks for the change. When will the update available to the Craft plugin store? Current change log on craft plugin store only shows up to v1.0.9

**Comment by alinistrate** [comment]
Hi Rishi,

This was fixed. It should be version 1.1.1 now.

THanks,
Alin
________________________________

**Comment by rsi2940** [comment]
Olivemenus updated to version 1.1.1, now I can add a new menu but all the existing menus are now broken here is a screenshot of the new menu 'test' with 'menu item' and a screenshot of the broken existing menu. Looks like it allows to create a new menu, but not able to edit the existing one. Using Craft v3.4.5
![image](https://user-images.githubusercontent.com/18317148/74247450-0c281880-4cb4-11ea-9d8a-903a48105914.png)
![image](https://user-images.githubusercontent.com/18317148/74247510-2a8e1400-4cb4-11ea-99e7-3c2e03295729.png)
