### ISSUE TITLE
Entries still showing on olivemenu admin listing even after deleted from entries page 

### ISSUE THREAD

**Issue by rakesmh14** [OliveStudio/olivemenus#35]
In olive menu admin section, deleted entries are also listed. For e.g, on removing any entry - single and and again creating same entry again in entries section then both deleted and newly created entry are listing in olivemenu admin single section.
Issue occurred in Craft CMS 3.x
Olive menu 1.0.9
Thanks!

**Comment by alinistrate** [comment]
Hi @rakesmh14 

Thanks for doing this. We merged the pull requests.

Alin

**Comment by rsi2940** [comment]
Thanks for the change. When will the update available to the Craft plugin store? Current change log on craft plugin store only shows up to 1.0.9
