### ISSUE TITLE
Updating to 1.1.1 in craft 3.4 causes this problem

### ISSUE THREAD

**Issue by martin-honcho** [OliveStudio/olivemenus#37]
Unknown Property – yii\base\UnknownPropertyException
Getting unknown property: olivestudio\olivemenus\records\OlivemenusItemsRecord::target

**Comment by alinistrate** [comment]
@martin-honcho 
We are looking into this issue. It will be solved by EOD today.

Thanks,
Alin

**Comment by alinistrate** [comment]
This was fixed. Please get the latest version

**Comment by martin-honcho** [comment]
Awesome, many thanks! Keep up the good work.
