### ISSUE TITLE
Custom Child Item breaks the link of parent item

### ISSUE THREAD

**Issue by christophstockinger** [OliveStudio/olivemenus#38]
I have a menu with several pages. One of them should have subpages. 
Once I add a normal subpage from Craft CMS is added and save everything fits.
But as soon as I add and save a custom menu item as a subpage, the page link of the parent element is removed from Craft CMS and the custom link of the inserted custom menu item is added.

This is not the desired behavior! I expect that the link of the parent element to the defined page in Craft CMS is kept and the added custom menu item links to the desired page.

**Comment by rakesmh14** [comment]
Hello,
I have also implemented multi level menu with the use of olivemenu - however I didn't encounter similar issue. Parent menu link is showing as expected as shown in screenshot: https://prnt.sc/r6rwkz
I think it might be related to custom navigation theming.
Thanks!

**Comment by rakesmh14** [comment]
Hello,
I have  created PR fixing parent menu link issue while adding custom menu as sub menu.
I hope this will help you in implementing custom menu as sub menu.
Thanks!

**Comment by christophstockinger** [comment]
Great! It works now!
