### ISSUE TITLE
CSRF Protection Breaks Menu Edit Form

### ISSUE THREAD

**Issue by grego3** [OliveStudio/olivemenus#4]
I have the `enableCsrfProtection` config setting set to `true` in my Craft CMS build. This breaks the Olive Menus edit menu items, new menu, and edit menu forms.

I'm running Olive Menus 1.0.0 on Craft CMS 2.6.2930

**Comment by alinistrate** [comment]
Hi, 

We pushed a fix for this. Please check.

Thanks.
