### ISSUE TITLE
Migrations are not run when updating the plugin

### ISSUE THREAD

**Issue by niektenhoopen** [OliveStudio/olivemenus#42]
The migration needed for multi-site is not automatically run.
Currently `./craft migrate/up --plugin=olivemenus` is needed manually

Will try to find time to fix it

**Comment by alinistrate** [comment]
@niektenhoopen 
Please check now with version 1.1.9 
I bumped the schema version and composer.json

Thank you,
Alin

**Comment by alinistrate** [comment]
This should be fixed now
