### ISSUE TITLE
Missing column 'site_id'

### ISSUE THREAD

**Issue by SamLNL** [OliveStudio/olivemenus#47]
When installing Olivemenus for the first time, it's missing the column 'site_id' in table 'olivemenus'. I fixed it by adding a 'site_id' column manually in the table 'olivemenus'.

**Comment by niektenhoopen** [comment]
@SamLNL Please don't make manual changes. It is fixed in the latest version along with some other stuff but I guess upgrading won't work for you because of your manual changes.

**Comment by alinistrate** [comment]
This issue is fixed
